version: '3'
services:
  node0:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node0
    image: galera-master
    volumes:
       - ./data0:/var/lib/mysql
       - ./node0.cnf:/etc/mysql/conf.d/galera.cnf
    environment:
       - MYSQL_ROOT_PASSWORD=1234
       - MYSQL_USER=galera
       - MYSQL_PASSWORD=1234
       - MYSQL_DATABASE=galera
    #entrypoint: sleep infinity
    restart: always

  node1:
    # build:
      # context: .
      # dockerfile: node-dockerfile
    container_name: node1
    image: galera-master
    volumes:
       - ./data1:/var/lib/mysql
       - ./node1.cnf:/etc/mysql/conf.d/galera.cnf
      #  - ./nodes-entrypoint.sh:/nodes-entrypoint.sh
    environment:
       - MYSQL_ROOT_PASSWORD=1234
       - MYSQL_USER=galera
       - MYSQL_PASSWORD=1234
       - MYSQL_DATABASE=galera
    depends_on: 
       - node0
    # entrypoint: /nodes-entrypoint.sh
    restart: always

  node2:
    # build:
      # context: .
      # dockerfile: node-dockerfile
    container_name: node2
    image: galera-master
    volumes:
       - ./data2:/var/lib/mysql
       - ./node2.cnf:/etc/mysql/conf.d/galera.cnf
      #  - ./nodes-entrypoint.sh:/nodes-entrypoint.sh
    environment:
       - MYSQL_ROOT_PASSWORD=1234
       - MYSQL_USER=galera
       - MYSQL_PASSWORD=1234
       - MYSQL_DATABASE=galera
    depends_on: 
       - node0
    # entrypoint: /nodes-entrypoint.sh
    restart: always